services:
  database:
    env_file:
      - .env.db
    ports:
      - "3309:3306"
    volumes:
      - development_data_database:/var/lib/mysql

  migration:
    build:
      target: migration-dev
    env_file:
      - .env
    volumes:
      - .:/app

  vendora_api:
    build:
      target: development
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    env_file:
      - .env
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/certs:/etc/nginx/certs:ro
volumes:
  development_data_database:
