services:
  database:
    env_file:
      - .env.db
    ports:
      - "3309:3306"
    volumes:
      - development_data_database:/var/lib/mysql

  migration:
    command: pnpm ts-node -r tsconfig-paths/register src/infrastructure/database/mysql/scripts/migrate.ts
    env_file:
      - .env
    volumes:
      - .:/app

  vendora_api:
    command: pnpm dev
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    env_file:
      - .env

volumes:
  development_data_database:
